// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain.rest;

import cs.ut.domain.rest.PlantsQueryViaRestTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PlantsQueryViaRestTest_Roo_Configurable {
    
    declare @type: PlantsQueryViaRestTest: @Configurable;
    
}
