// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain.bean;

import cs.ut.domain.bean.PlantDTO;

privileged aspect PlantDTO_Roo_JavaBean {
    
    public String PlantDTO.getName() {
        return this.name;
    }
    
    public void PlantDTO.setName(String name) {
        this.name = name;
    }
    
}
