
package cs.ut.domain.soap.client.po;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PurchaseOrderSOAPServiceService", targetNamespace = "http://service.soap.domain.ut.cs/", wsdlLocation = "http://localhost:8081/Rentit/PurchaseOrderSOAPService?wsdl")
public class PurchaseOrderSOAPServiceService
    extends Service
{

    private final static URL PURCHASEORDERSOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PURCHASEORDERSOAPSERVICESERVICE_EXCEPTION;
    private final static QName PURCHASEORDERSOAPSERVICESERVICE_QNAME = new QName("http://service.soap.domain.ut.cs/", "PurchaseOrderSOAPServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/Rentit/PurchaseOrderSOAPService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PURCHASEORDERSOAPSERVICESERVICE_WSDL_LOCATION = url;
        PURCHASEORDERSOAPSERVICESERVICE_EXCEPTION = e;
    }

    public PurchaseOrderSOAPServiceService() {
        super(__getWsdlLocation(), PURCHASEORDERSOAPSERVICESERVICE_QNAME);
    }

    public PurchaseOrderSOAPServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PURCHASEORDERSOAPSERVICESERVICE_QNAME, features);
    }

    public PurchaseOrderSOAPServiceService(URL wsdlLocation) {
        super(wsdlLocation, PURCHASEORDERSOAPSERVICESERVICE_QNAME);
    }

    public PurchaseOrderSOAPServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PURCHASEORDERSOAPSERVICESERVICE_QNAME, features);
    }

    public PurchaseOrderSOAPServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PurchaseOrderSOAPServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PurchaseOrderSOAPService
     */
    @WebEndpoint(name = "PurchaseOrderSOAPServicePort")
    public PurchaseOrderSOAPService getPurchaseOrderSOAPServicePort() {
        return super.getPort(new QName("http://service.soap.domain.ut.cs/", "PurchaseOrderSOAPServicePort"), PurchaseOrderSOAPService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PurchaseOrderSOAPService
     */
    @WebEndpoint(name = "PurchaseOrderSOAPServicePort")
    public PurchaseOrderSOAPService getPurchaseOrderSOAPServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.domain.ut.cs/", "PurchaseOrderSOAPServicePort"), PurchaseOrderSOAPService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PURCHASEORDERSOAPSERVICESERVICE_EXCEPTION!= null) {
            throw PURCHASEORDERSOAPSERVICESERVICE_EXCEPTION;
        }
        return PURCHASEORDERSOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
