// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.SiteEngineer;

privileged aspect SiteEngineer_Roo_JavaBean {
    
    public String SiteEngineer.getName() {
        return this.name;
    }
    
    public void SiteEngineer.setName(String name) {
        this.name = name;
    }
    
}
