// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.Site;

privileged aspect Site_Roo_JavaBean {
    
    public String Site.getName() {
        return this.name;
    }
    
    public void Site.setName(String name) {
        this.name = name;
    }
    
}
