// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain.rest;

import cs.ut.domain.rest.PlantResource;

privileged aspect PlantResource_Roo_JavaBean {
    
    public long PlantResource.getIdentifier() {
        return this.identifier;
    }
    
    public void PlantResource.setIdentifier(long identifier) {
        this.identifier = identifier;
    }
    
}
