// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.PlantHireRequest;
import cs.ut.domain.PlantHireRequestDataOnDemand;
import cs.ut.domain.PlantHireRequestIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PlantHireRequestIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PlantHireRequestIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PlantHireRequestIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PlantHireRequestIntegrationTest: @Transactional;
    
    @Autowired
    PlantHireRequestDataOnDemand PlantHireRequestIntegrationTest.dod;
    
    @Test
    public void PlantHireRequestIntegrationTest.testCountPlantHireRequests() {
        Assert.assertNotNull("Data on demand for 'PlantHireRequest' failed to initialize correctly", dod.getRandomPlantHireRequest());
        long count = PlantHireRequest.countPlantHireRequests();
        Assert.assertTrue("Counter for 'PlantHireRequest' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PlantHireRequestIntegrationTest.testFindPlantHireRequest() {
        PlantHireRequest obj = dod.getRandomPlantHireRequest();
        Assert.assertNotNull("Data on demand for 'PlantHireRequest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PlantHireRequest' failed to provide an identifier", id);
        obj = PlantHireRequest.findPlantHireRequest(id);
        Assert.assertNotNull("Find method for 'PlantHireRequest' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PlantHireRequest' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PlantHireRequestIntegrationTest.testFindAllPlantHireRequests() {
        Assert.assertNotNull("Data on demand for 'PlantHireRequest' failed to initialize correctly", dod.getRandomPlantHireRequest());
        long count = PlantHireRequest.countPlantHireRequests();
        Assert.assertTrue("Too expensive to perform a find all test for 'PlantHireRequest', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PlantHireRequest> result = PlantHireRequest.findAllPlantHireRequests();
        Assert.assertNotNull("Find all method for 'PlantHireRequest' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PlantHireRequest' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PlantHireRequestIntegrationTest.testFindPlantHireRequestEntries() {
        Assert.assertNotNull("Data on demand for 'PlantHireRequest' failed to initialize correctly", dod.getRandomPlantHireRequest());
        long count = PlantHireRequest.countPlantHireRequests();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PlantHireRequest> result = PlantHireRequest.findPlantHireRequestEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PlantHireRequest' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PlantHireRequest' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PlantHireRequestIntegrationTest.testFlush() {
        PlantHireRequest obj = dod.getRandomPlantHireRequest();
        Assert.assertNotNull("Data on demand for 'PlantHireRequest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PlantHireRequest' failed to provide an identifier", id);
        obj = PlantHireRequest.findPlantHireRequest(id);
        Assert.assertNotNull("Find method for 'PlantHireRequest' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPlantHireRequest(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PlantHireRequest' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PlantHireRequestIntegrationTest.testMergeUpdate() {
        PlantHireRequest obj = dod.getRandomPlantHireRequest();
        Assert.assertNotNull("Data on demand for 'PlantHireRequest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PlantHireRequest' failed to provide an identifier", id);
        obj = PlantHireRequest.findPlantHireRequest(id);
        boolean modified =  dod.modifyPlantHireRequest(obj);
        Integer currentVersion = obj.getVersion();
        PlantHireRequest merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PlantHireRequest' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PlantHireRequestIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PlantHireRequest' failed to initialize correctly", dod.getRandomPlantHireRequest());
        PlantHireRequest obj = dod.getNewTransientPlantHireRequest(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PlantHireRequest' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PlantHireRequest' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PlantHireRequest' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PlantHireRequestIntegrationTest.testRemove() {
        PlantHireRequest obj = dod.getRandomPlantHireRequest();
        Assert.assertNotNull("Data on demand for 'PlantHireRequest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PlantHireRequest' failed to provide an identifier", id);
        obj = PlantHireRequest.findPlantHireRequest(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PlantHireRequest' with identifier '" + id + "'", PlantHireRequest.findPlantHireRequest(id));
    }
    
}
