// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.SiteEngineer;
import cs.ut.domain.SiteEngineerDataOnDemand;
import cs.ut.repository.SiteEngineerRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SiteEngineerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SiteEngineerDataOnDemand: @Component;
    
    private Random SiteEngineerDataOnDemand.rnd = new SecureRandom();
    
    private List<SiteEngineer> SiteEngineerDataOnDemand.data;
    
    @Autowired
    SiteEngineerRepository SiteEngineerDataOnDemand.siteEngineerRepository;
    
    public SiteEngineer SiteEngineerDataOnDemand.getNewTransientSiteEngineer(int index) {
        SiteEngineer obj = new SiteEngineer();
        setEmail(obj, index);
        setFirstName(obj, index);
        setLastName(obj, index);
        return obj;
    }
    
    public void SiteEngineerDataOnDemand.setEmail(SiteEngineer obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    public void SiteEngineerDataOnDemand.setFirstName(SiteEngineer obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void SiteEngineerDataOnDemand.setLastName(SiteEngineer obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    public SiteEngineer SiteEngineerDataOnDemand.getSpecificSiteEngineer(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SiteEngineer obj = data.get(index);
        Long id = obj.getId();
        return siteEngineerRepository.findOne(id);
    }
    
    public SiteEngineer SiteEngineerDataOnDemand.getRandomSiteEngineer() {
        init();
        SiteEngineer obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return siteEngineerRepository.findOne(id);
    }
    
    public boolean SiteEngineerDataOnDemand.modifySiteEngineer(SiteEngineer obj) {
        return false;
    }
    
    public void SiteEngineerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = siteEngineerRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SiteEngineer' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SiteEngineer>();
        for (int i = 0; i < 10; i++) {
            SiteEngineer obj = getNewTransientSiteEngineer(i);
            try {
                siteEngineerRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            siteEngineerRepository.flush();
            data.add(obj);
        }
    }
    
}
