// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.Site;
import cs.ut.domain.SiteDataOnDemand;
import cs.ut.domain.SiteIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SiteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SiteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SiteIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SiteIntegrationTest: @Transactional;
    
    @Autowired
    SiteDataOnDemand SiteIntegrationTest.dod;
    
    @Test
    public void SiteIntegrationTest.testCountSites() {
        Assert.assertNotNull("Data on demand for 'Site' failed to initialize correctly", dod.getRandomSite());
        long count = Site.countSites();
        Assert.assertTrue("Counter for 'Site' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SiteIntegrationTest.testFindSite() {
        Site obj = dod.getRandomSite();
        Assert.assertNotNull("Data on demand for 'Site' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Site' failed to provide an identifier", id);
        obj = Site.findSite(id);
        Assert.assertNotNull("Find method for 'Site' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Site' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SiteIntegrationTest.testFindAllSites() {
        Assert.assertNotNull("Data on demand for 'Site' failed to initialize correctly", dod.getRandomSite());
        long count = Site.countSites();
        Assert.assertTrue("Too expensive to perform a find all test for 'Site', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Site> result = Site.findAllSites();
        Assert.assertNotNull("Find all method for 'Site' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Site' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SiteIntegrationTest.testFindSiteEntries() {
        Assert.assertNotNull("Data on demand for 'Site' failed to initialize correctly", dod.getRandomSite());
        long count = Site.countSites();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Site> result = Site.findSiteEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Site' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Site' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SiteIntegrationTest.testFlush() {
        Site obj = dod.getRandomSite();
        Assert.assertNotNull("Data on demand for 'Site' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Site' failed to provide an identifier", id);
        obj = Site.findSite(id);
        Assert.assertNotNull("Find method for 'Site' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySite(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Site' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SiteIntegrationTest.testMergeUpdate() {
        Site obj = dod.getRandomSite();
        Assert.assertNotNull("Data on demand for 'Site' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Site' failed to provide an identifier", id);
        obj = Site.findSite(id);
        boolean modified =  dod.modifySite(obj);
        Integer currentVersion = obj.getVersion();
        Site merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Site' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SiteIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Site' failed to initialize correctly", dod.getRandomSite());
        Site obj = dod.getNewTransientSite(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Site' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Site' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Site' identifier to no longer be null", obj.getId());
    }
    
}
