// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.Site;
import cs.ut.domain.SiteDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SiteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SiteDataOnDemand: @Component;
    
    private Random SiteDataOnDemand.rnd = new SecureRandom();
    
    private List<Site> SiteDataOnDemand.data;
    
    public Site SiteDataOnDemand.getNewTransientSite(int index) {
        Site obj = new Site();
        setName(obj, index);
        return obj;
    }
    
    public void SiteDataOnDemand.setName(Site obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Site SiteDataOnDemand.getSpecificSite(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Site obj = data.get(index);
        Long id = obj.getId();
        return Site.findSite(id);
    }
    
    public Site SiteDataOnDemand.getRandomSite() {
        init();
        Site obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Site.findSite(id);
    }
    
    public boolean SiteDataOnDemand.modifySite(Site obj) {
        return false;
    }
    
    public void SiteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Site.findSiteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Site' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Site>();
        for (int i = 0; i < 10; i++) {
            Site obj = getNewTransientSite(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
