// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.SupplierIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SupplierIntegrationTest_Roo_Configurable {
    
    declare @type: SupplierIntegrationTest: @Configurable;
    
}
